### ISSUE TITLE
Proposal: Add ESLint Unicorn Plugin

### ISSUE THREAD

**Issue by davidwarrington** [strawberry/eslint-config-strawberry#6]
[ESLint Unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn)

Some of us have glanced at this library before. I think it has some handy rules that would be worthwhile to add.

For starters, we can enforce things like the filename casing, which we currently mix and match a bit.

It has rules for preferring more modern syntax and methods too, such as the spread operator instead of `Array.from`, using `Array.includes` instead of `Array.indexOf` (in places where `Array.includes` is the intended functionality of course), and sticking to `Element.querySelector/querySelectorAll` instead of mixing and matching methods like `getElementById` and `getElementsByTagName`.

I think the primary benefit of some of these rules would simply be making it easier for people to find more modern, or better solutions to problems. For example, I find that often people aren't aware of Array methods like `.find` and `.some`. Also I think I could benefit from its `better-regex` rule. A linter that highlights things like that for you seems like a good idea.

Also I **really** like the idea of the `no-abusive-eslint-disable` and `expiring-todo-comments` rules. Disabling a rule is fine with good reason, but it's risky disabling all just to avoid a linter error. And in fairness I can't imagine myself really making use of the expiring todo comments rule, it just seems like a good idea to be held to a promise to resolve something you've marked as "todo".

I don't have a plan for exactly which rules we'd enable and disable at the moment, but I am interested in more input.

**Comment by tomnoble20** [comment]
Sounds good to me.

**Comment by kayrunm** [comment]
Sounds good to me; I like the expiring todo-comments. Would've come in handy on Woodlodge as I wouldn't have left that comment in at the top!
